---
abstract: 'inotify interface for POE'
author:
  - 'Philip Gwyn <gwyn -at- cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Inotify
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1
  Data::Dump: 1
  File::Path: 2.08
  Linux::Inotify2: 1
  POE: 1.284
  POE::Session::PlainCall: 0.03
version: 0.0200
